### ISSUE TITLE
Copying text with link text points to URL of the link text instead of that of the page

### ISSUE THREAD

**Issue by zbh531** [hnakamur/FormatLink-Chrome#14]
Hi! I really enjoy *“Format Link as **Markdown**”* using this extension to make notes. However, when I copy text with some link text, the variable `{{url}}` points to the URL of the link text instead of that of the page, which does not make sense in terms of note-taking.

#### Example:
When I browse the *[Cat - Wikipedia](https://en.wikipedia.org/wiki/Cat)* page, I'd like to extract the first sentence in the fourth paragraph *"Cats were first domesticated in the [Near East](https://en.wikipedia.org/wiki/Near_East) around 7500 BC."*, where the text ***Near East*** is with a hyperlink.

**"Format Link as Markdown (default format)" Result:** [Cats were first domesticated in the Near East around 7500 BC.](https://en.wikipedia.org/wiki/Near_East)
**Source Mode:** \[Cats were first domesticated in the Near East around 7500 BC.\](https://en.wikipedia.org/wiki/Near_East)

As can be seen from the result, the generated `{{url}}` variable points to the URL of the link text ***Near East*** (i.e., *https://en.wikipedia.org/wiki/Near_East*) instead of the URL of the ***page*** (i.e., *https://en.wikipedia.org/wiki/Cat*).

This does not make any sense to me, because what I'd like to make notes for is the ***Cat - Wikipedia*** page rather than ***link text*** in that page. The fact that the whole copied Markdown sentence is directed to the link of text in that sentence is weird.

Thank you in advance for your attention to this issue.

**Comment by hnakamur** [comment]
That behavior of `url` variable is exactly what I want.
Instead I can add another variable `pageUrl` which always expands to the URL of the page.
Is that OK with you?
Then I will merge [Add pageUrl variable by hnakamur · Pull Request #15 · hnakamur/FormatLink-Chrome](https://github.com/hnakamur/FormatLink-Chrome/pull/15) and release new version 4.1.0.

**Comment by zbh531** [comment]
> That behavior of `url` variable is exactly what I want. Instead I can add another variable `pageUrl` which always expands to the URL of the page. Is that OK with you? Then I will merge [Add pageUrl variable by hnakamur · Pull Request #15 · hnakamur/FormatLink-Chrome](https://github.com/hnakamur/FormatLink-Chrome/pull/15) and release new version 4.1.0.

That's a really great idea! I appreciate your intention to help with this matter. Thank you so much for your help!
