### ISSUE TITLE
Default Font and Size

### ISSUE THREAD

**Issue by dlfuller** [hnakamur/FormatLink-Chrome#16]
Thanks for a versatile and useful extension.  Is there a way to add type font and size in the format of a pasted HTML link?  A link now appears when pasted as 12pt Times and my (preferred) default is 13pt Georgia.

**Comment by hnakamur** [comment]
Hi, you can add `style` attribute to the format value of your HTML option:
```
<a href="{{url.s("\"","&quot;")}}" style="font-family: Georgia; font-size:13pt;">{{text.s("<","&lt;")}}</a>
```

Hope this helps.

**Comment by dlfuller** [comment]
> On 06/13/2022, at 9:20 AM, Hiroaki Nakamura ***@***.***> wrote:
> 
> <a href="{{url.s("\"","&quot;")}}" style="font-family: Georgia; font-size:13pt;">{{text.s("<","&lt;")}}</a>

Immensely helpful.  That's the answer.  Thanks!!!

I had been trying something similar with a style attribute.  But had become frustrated with the syntax.  The placement of style and punctuation symbols not being correct.

A minor detail is the change in your example from 13pt to 13px.

Recommended HTML->   <a href="{{url.s("\"","&quot;")}}" style="font-family: Georgia; font-size:13pt;">{{text.s("<","&lt;")}}</a>
	✿ Our favorite set —  <https://copypastecharacter.com/>CopyPasteCharacter.com <http://copypastecharacter.com/>

Revised HTML->   <a href="{{url.s("\"","&quot;")}}" style="font-family: Georgia; font-size:13px;">{{text.s("<","&lt;")}}</a>
	✿ Our favorite set —  <https://copypastecharacter.com/>CopyPasteCharacter.com <http://copypastecharacter.com/>

Thanks again for your help with a quick response.

--Don

**Comment by hnakamur** [comment]
I'm glad it helps.
I'm closing this issue now.
