### ISSUE TITLE
Documentation on required permissions

### ISSUE THREAD

**Issue by uamv** [hnakamur/FormatLink-Chrome#20]
As of version 5.0.0, this extension requires allowing permissions to:

- Read and change all your data on all websites

Any documentation on what feature is making use of this permissions and why this is now required by the extension?

**Comment by hnakamur** [comment]
Thanks for your comment.

I added "Permissions required by this extension" section to document at [the page for this extension at the Chrome Web store](https://chromewebstore.google.com/detail/format-link/pocemhmkmchpgamlnocemnbhlcjcbjgg).
I also added it to README of this repository at [Add permissions section to README by hnakamur · Pull Request #23 · hnakamur/FormatLink-Chrome](https://github.com/hnakamur/FormatLink-Chrome/pull/23).

**Comment by uamv** [comment]
Excellent! Thank you for the clarification and documenting this.

**Comment by Alphabet1226** [comment]
I'm sorry, but I still don't understand. Why didn't you need this permission before? Because it's a very high-level permission, so I feel deeply puzzled.
